In [1]:
# Coluring  in pandas:-
# Importing pandas as pd:-
# Know read the html_file
# Take the link from the google as:-
# "Https://en.wikipedia.org/wiki/List_of_highest-grossing_films"

import pandas as pd
df=pd.read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_films")

In [2]:
# Take the database :-
# Call the database as "x":-
# "x=df[0]"
# Call "X"

x=df[0]
x

,Rank,Peak,Title,Worldwide gross,Year,Ref
0,1,1,Avatar,"$2,923,706,026",2009,[# 1][# 2]
1,2,1,Avengers: Endgame,"$2,797,501,328",2019,[# 3][# 4]
2,3,3,Avatar: The Way of Water,"$2,320,250,281",2022,[# 5][# 6]
3,4,1,Titanic,"T$2,257,844,554",1997,[# 7][# 8]
4,5,3,Star Wars: The Force Awakens,"$2,068,223,624",2015,[# 9][# 10]
5,6,4,Avengers: Infinity War,"$2,048,359,754",2018,[# 11][# 12]
6,7,6,Spider-Man: No Way Home,"$1,921,847,111",2021,[# 13][# 14]
7,8,3,Jurassic World,"$1,671,537,444",2015,[# 15][# 16]
8,9,7,The Lion King,"$1,656,943,394",2019,[# 17][# 4]
9,10,3,The Avengers,"$1,518,815,515",2012,[# 18][# 19]
10,11,4,Furious 7,"$1,515,341,399",2015,[# 20][# 21]
11,12,11,Top Gun: Maverick,"$1,495,696,292",2022,[# 22][# 23]
12,13,10,Frozen II,"$1,450,026,933",2019,[# 24][# 25]
13,14,14,Barbie,"$1,445,638,421",2023,[# 26][# 27]
14,15,5,Avengers: Age of Ultron,"$1,402,809,540",2015,[# 28][# 21]
15,16,15,The Super Mario Bros. Movie,"$1,361,992,475",2023,[# 29][# 30]
16,17,9,Black Panther,"$1,347,280,838",2018,[# 31][# 32]
17,18,3,Harry Potter and the Deathly Hallows â€“ Part 2,"$1,342,139,727",2011,[# 33][# 34]
18,19,9,Star Wars: The Last Jedi,"$1,332,539,889",2017,[# 35][# 36]
19,20,12,Jurassic World: Fallen Kingdom,"$1,308,473,425",2018,[# 37][# 12]
20,21,5,Frozen,"F$1,290,000,000",2013,[# 38][# 39]
21,22,10,Beauty and the Beast,"$1,263,521,126",2017,[# 40][# 41]
22,23,15,Incredibles 2,"$1,242,805,359",2018,[# 42][# 12]
23,24,11,The Fate of the Furious,"F8$1,238,764,765",2017,[# 43][# 41]
24,25,5,Iron Man 3,"$1,214,811,252",2013,[# 44][# 45]
25,26,10,Minions,"$1,159,444,662",2015,[# 46][# 16]
26,27,12,Captain America: Civil War,"$1,153,337,496",2016,[# 47][# 48]
27,28,20,Aquaman,"$1,148,528,393",2018,[# 49][# 12]
28,29,2,The Lord of the Rings: The Return of the King,"$1,147,997,407",2003,[# 50][# 51]
29,30,24RK,Spider-Man: Far From Home,"$1,131,927,996",2019,[# 52][# 4]
30,31,23RK,Captain Marvel,"$1,128,274,794",2019,[# 53][# 54]
31,32,5RK,Transformers: Dark of the Moon,"$1,123,794,079",2011,[# 55][# 34]
32,33,7,Skyfall,"$1,108,569,499",2012,[# 56][# 57]
33,34,10,Transformers: Age of Extinction,"$1,104,054,072",2014,[# 58][# 59]
34,35,7,The Dark Knight Rises,"$1,081,169,825",2012,[# 60][# 61]
35,36,31,Joker,"$1,074,458,282",2019,[# 62][# 25]
36,37,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019,[# 63][# 25]
37,38,30,Toy Story 4,"$1,073,394,593",2019,[# 64][# 4]
38,39,4TS3,Toy Story 3,"$1,066,970,811",2010,[# 65][# 66]
39,40,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006,[# 67][# 68]
40,41,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016,[# 69][# 70]
41,42,34,Aladdin,"$1,050,693,953",2019,[# 71][# 4]
42,43,2,Star Wars: Episode I â€“ The Phantom Menace,"$1,046,515,409",1999,[# 72][# 8]
43,44,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011,[# 73][# 66]
44,45,1,Jurassic Park,"$1,037,535,230",1993,[# 74][# 75]
45,46,24,Despicable Me 3,"$1,034,800,131",2017,[# 76][# 41]
46,47,22,Finding Dory,"$1,028,570,942",2016,[# 77][# 78]
47,48,5,Alice in Wonderland,"$1,025,468,216",2010,[# 79][# 80]
48,49,24,Zootopia,"$1,023,784,195",2016,[# 81][# 48]
49,50,14,The Hobbit: An Unexpected Journey,"$1,017,030,651",2012,[# 82][# 83]

In [3]:
# 1> Method:-

In [15]:
# Make a def function as color_negative_red:-
# In the def function create a If-Else condition:-
# If the value is less than 2000 color it as red:-
# Elif the value is greater than 2000 color it as green:-
# Otherwise else color the rest as black:-
# And return the color as "%s":-

def color_negative_red(value):
    if value < 2000:
        color = 'red'
    elif value > 2000:
        color = 'green'
    else:
        color = 'black'
    return 'color: %s' % color

In [16]:
# Styling the database "X" and applymap and set the color as red or green:-

x.style.applymap(color_negative_red,subset=["Year"])

C:\Users\parul\AppData\Local\Temp\ipykernel_22172\968553421.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  x.style.applymap(color_negative_red,subset=["Year"])

In [5]:
# Styling the properties on the behalf of back-ground color and color:-

x.style.set_properties(**{'background-color': 'pink','color': 'blue'})

In [6]:
# Styling the database "X" as highlight_min and color it as purple:-

x.style.highlight_min(color="purple",axis=0)

In [7]:
#  Styling the database "X" as highlight_max and color it as red:-

x.style.highlight_max(color="red",axis=0)

In [8]:
# Setting background color as gradient color as cmap="Spectral":-

x.style.background_gradient(cmap="Spectral")

In [9]:
# Making a def function as row_style :-
# Creating a If-Else condition:-
# If the year is less than "2015" than color the row as "pink":-
# Else color the rest year as "purple":-
# At the end style the database as "apply" at axix=1 or row:-

def row_style(row):
    if row.Year < 2015:
        return pd.Series('background-color: pink', row.index)
    else:
        return pd.Series('background-color: purple', row.index)

x.style.apply(row_style, axis=1)

In [10]:
# Making a def function as column_style :-
# Creating a If-Else condition:-
# If the year is less than "2015" than color the column as "purple":-
# Else color the rest year as "orange":-
# At the end style the database as "apply" at axix=1 or column:-

def column_style(column):
    if column.Year < 2015:
        return pd.Series('background-color: purple', column.index)
    else:
        return pd.Series('background-color: orange', column.index)

x.style.apply(column_style, axis=1)

In [11]:
# Styling the background-gradiant as green through the "set-precision":-

y=x.style.background_gradient("Greens").set_precision(2).highlight_null('black').highlight_min(axis=0, color='red').highlight_max(axis=0, color='pink')
y

# Here the "set-precision" module is not working.

AttributeError: 'Styler' object has no attribute 'set_precision'

In [12]:
# Styling the head as highlight_min in the"purple" color:-

x.head().style.highlight_min(color='purple',axis=0)

In [13]:
y=x.head().style.background_gradient("Greens").set_precision(2).highlight_null('black').highlight_min(axis=0, color='red').highlight_max(axis=0, color='pink')
y

# Here the"set-precision" module is not working.

AttributeError: 'Styler' object has no attribute 'set_precision'